// docs/.vitepress/theme/components/assistant/Assistant.jsx
import { DynamicIcon } from '@nild/icons';
import { cnMerge } from '@nild/shared';
import React, { useCallback, useEffect, useState } from 'react';
import i18n from '../../../../../locales/index';
import ChatPanel from './components/ChatPanel';
import ConnectPanel from './components/ConnectPanel';
import Header from './components/Header';
import { AssistantProvider } from './contexts/AssistantContext';
import { useDraggable } from './hooks/useDraggable';
import { useRuntime } from './hooks/useRuntime';

const TRIGGER_SIZE = { w: 48, h: 48 };
const MAX_DIALOG_SIZE = { w: 380, h: 560 };
const SAFE_PADDING = 16;

const clampValue = (value, min, max) => Math.max(min, Math.min(value, max));

const getDialogSize = viewport => ({
    w: Math.min(
        MAX_DIALOG_SIZE.w,
        viewport.w > SAFE_PADDING * 2 ? Math.max(TRIGGER_SIZE.w, viewport.w - SAFE_PADDING * 2) : MAX_DIALOG_SIZE.w,
    ),
    h: Math.min(
        MAX_DIALOG_SIZE.h,
        viewport.h > SAFE_PADDING * 2 ? Math.max(TRIGGER_SIZE.h, viewport.h - SAFE_PADDING * 2) : MAX_DIALOG_SIZE.h,
    ),
});

const getInitialViewport = () => {
    if (typeof window === 'undefined') {
        return { w: 0, h: 0 };
    }

    return { w: window.innerWidth, h: window.innerHeight };
};

const getInitialPosition = viewport => ({
    x: Math.max(SAFE_PADDING, viewport.w - TRIGGER_SIZE.w - SAFE_PADDING),
    y: Math.max(SAFE_PADDING, viewport.h - TRIGGER_SIZE.h - SAFE_PADDING),
});

const Assistant = ({ locale = 'zh-CN', base = '/', routePath = '', navigate }) => {
    const [mounted, setMounted] = useState(false);
    const [opened, setOpened] = useState(false);
    const [viewport, setViewport] = useState(getInitialViewport);
    const [position, setPosition] = useState(() => getInitialPosition(getInitialViewport()));
    const dialogSize = getDialogSize(viewport);
    const size = opened ? dialogSize : TRIGGER_SIZE;

    const clampPosition = useCallback(
        (x, y, targetOpened = opened, targetViewport = viewport) => {
            const targetSize = targetOpened ? getDialogSize(targetViewport) : TRIGGER_SIZE;
            const maxX = Math.max(SAFE_PADDING, targetViewport.w - targetSize.w - SAFE_PADDING);
            const maxY = Math.max(SAFE_PADDING, targetViewport.h - targetSize.h - SAFE_PADDING);

            return {
                x: clampValue(x, SAFE_PADDING, maxX),
                y: clampValue(y, SAFE_PADDING, maxY),
            };
        },
        [opened, viewport],
    );

    const getAnchorOffset = useCallback(
        (targetOpened, targetDialogSize = dialogSize) => {
            if (!targetOpened) {
                return {
                    x: TRIGGER_SIZE.w / 2,
                    y: TRIGGER_SIZE.h / 2,
                };
            }

            return {
                x: targetDialogSize.w - TRIGGER_SIZE.w / 2,
                y: targetDialogSize.h - TRIGGER_SIZE.h / 2,
            };
        },
        [dialogSize],
    );

    const toggleOpen = useCallback(() => {
        const nextOpened = !opened;
        const currentAnchor = getAnchorOffset(opened, dialogSize);
        const nextAnchor = getAnchorOffset(nextOpened, dialogSize);
        const originX = position.x + currentAnchor.x;
        const originY = position.y + currentAnchor.y;
        const nextX = originX - nextAnchor.x;
        const nextY = originY - nextAnchor.y;

        setPosition(clampPosition(nextX, nextY, nextOpened));
        setOpened(nextOpened);
    }, [clampPosition, dialogSize, getAnchorOffset, opened, position.x, position.y]);

    const { dragging, onDragStart } = useDraggable({
        position,
        setPosition,
        clamp: (x, y) => clampPosition(x, y, opened),
        onClick: toggleOpen,
    });
    const openPanel = useCallback(() => {
        setPosition(current => {
            const currentAnchor = getAnchorOffset(opened, dialogSize);
            const nextAnchor = getAnchorOffset(true, dialogSize);
            const originX = current.x + currentAnchor.x;
            const originY = current.y + currentAnchor.y;

            return clampPosition(originX - nextAnchor.x, originY - nextAnchor.y, true);
        });
        setOpened(true);
    }, [clampPosition, dialogSize, getAnchorOffset, opened]);

    const runtime = useRuntime({
        base,
        locale,
        onOpen: openPanel,
    });

    useEffect(() => {
        setMounted(true);

        const updateViewport = () => {
            const nextViewport = { w: window.innerWidth, h: window.innerHeight };
            const nextSize = opened ? getDialogSize(nextViewport) : TRIGGER_SIZE;
            const maxX = Math.max(SAFE_PADDING, nextViewport.w - nextSize.w - SAFE_PADDING);
            const maxY = Math.max(SAFE_PADDING, nextViewport.h - nextSize.h - SAFE_PADDING);

            setViewport(nextViewport);
            setPosition(current => ({
                x: clampValue(current.x, SAFE_PADDING, maxX),
                y: clampValue(current.y, SAFE_PADDING, maxY),
            }));
        };

        updateViewport();
        window.addEventListener('resize', updateViewport);

        return () => window.removeEventListener('resize', updateViewport);
    }, [opened]);

    if (!mounted) {
        return null;
    }

    return (
        <AssistantProvider locale={locale} navigate={navigate} routePath={routePath} runtime={runtime}>
            <div
                className={cnMerge(
                    'nd-assistant-root vp-raw fixed z-39 overflow-hidden font-nd shadow-2xl will-change-[left,top,width,height,border-radius]',
                    dragging
                        ? 'transition-none'
                        : 'transition-[left,top,width,height,border-radius,background-color] ease-[cubic-bezier(0.2,0.85,0.25,1)]',
                    opened ? 'rounded-xl' : 'rounded-2xl',
                )}
                style={{
                    left: position.x,
                    top: position.y,
                    width: size.w,
                    height: size.h,
                }}
            >
                <div
                    className={cnMerge(
                        'absolute inset-0 flex origin-bottom-right flex-col bg-subtle text-main transition-[opacity,transform] ease-[cubic-bezier(0.22,1,0.36,1)]',
                        opened
                            ? 'pointer-events-auto scale-100 opacity-100 delay-75'
                            : 'pointer-events-none scale-95 opacity-0',
                    )}
                    aria-hidden={!opened}
                    inert={opened ? undefined : ''}
                >
                    <Header onClose={toggleOpen} onDragStart={onDragStart} />
                    {!runtime.connected ? <ConnectPanel /> : <ChatPanel />}
                </div>
                <button
                    className={cnMerge(
                        'absolute inset-0 flex items-center justify-center bg-vp-accent-soft text-brand transition-[opacity,transform,background-color] ease-out cursor-pointer select-none hover:text-brand-hover active:text-brand-active',
                        opened ? 'pointer-events-none opacity-0' : 'pointer-events-auto opacity-100',
                    )}
                    type="button"
                    aria-label={i18n.t('assistant.open', { language: locale })}
                    aria-hidden={opened}
                    tabIndex={opened ? -1 : undefined}
                    onMouseDown={onDragStart}
                >
                    <DynamicIcon name="message" variant="filled" className="text-[22px]" />
                </button>
            </div>
        </AssistantProvider>
    );
};

export default Assistant;

// docs/.vitepress/theme/components/assistant/Assistant.vue
<template>
    <Teleport v-if="mounted" to="body">
        <div
            :class="[
                'vp-raw fixed z-[9999] overflow-hidden text-brand-contrast font-nd shadow-2xl rounded-xl',
                dragging ? 'transition-none' : 'transition-[width,height,top,left,border-radius]',
            ]"
            :style="{
                left: `${position.x}px`,
                top: `${position.y}px`,
                width: `${containerSize.w}px`,
                height: `${containerSize.h}px`,
                ...(!opened ? { borderRadius: '50%' } : {}),
            }"
        >
            <Transition
                enter-active-class="transition-opacity ease-out delay-150"
                leave-active-class="transition-opacity ease-in"
                leave-to-class="opacity-0"
                @after-leave="llm.clear"
            >
                <div
                    v-if="opened"
                    class="absolute inset-x-0 top-0 bg-subtle text-main flex flex-col"
                    :style="{ bottom: `${triggerSize.h}px` }"
                >
                    <Dialog
                        :llm="llm"
                        :rag="rag"
                        @header-mousedown="onDragStart"
                        @close="toggleOpen"
                        @retry="handleRetry"
                    >
                        <template #input>
                            <PromptBox
                                v-model="promptValue"
                                :placeholder="promptPlaceholder"
                                :disabled="!promptEnabled"
                                :sendable="promptSendable"
                                @send="sendMessage"
                            />
                        </template>
                    </Dialog>
                </div>
            </Transition>
            <div
                :class="[
                    'absolute inset-x-0 bottom-0',
                    'flex items-center justify-center',
                    'bg-brand transition-colors cursor-pointer select-none',
                    'hover:bg-brand-hover',
                    'active:bg-brand-active',
                ]"
                :style="{ height: `${triggerSize.h}px` }"
                @mousedown="onDragStart"
            >
                <ChatIcon class="size-5" />
            </div>
        </div>
    </Teleport>
</template>

<script setup>
import { computed, onMounted, onUnmounted, provide, ref, watch } from 'vue';
import { useData } from 'vitepress';
import ChatIcon from '../../icons/Chat.vue';
import i18n from '../../../../../locales/index.js';
import Dialog from './Dialog.vue';
import PromptBox from './PromptBox.vue';
import { createRAGPrompt, RAGStatus } from './rag.shared.js';
import { useDraggable } from './useDraggable.js';
import { DEFAULT_SYSTEM_PROMPT, LLMStatus, useLLM } from './useLLM.js';
import { useRAG } from './useRAG.js';

const props = defineProps({
    safePadding: {
        type: Number,
        default: 16,
    },
    triggerSize: {
        type: Object,
        default: () => ({ w: 48, h: 48 }),
    },
    dialogSize: {
        type: Object,
        default: () => ({ w: 320, h: 528 }),
    },
});

const { lang, site } = useData();
const t = key => i18n.t(key, { language: lang.value });

provide('assistant:t', t);

const llm = useLLM({ t });
const rag = useRAG({
    locale: lang,
    base: computed(() => site.value.base || '/'),
    t,
});

const promptValue = ref('');
const promptEnabled = computed(() => llm.status === LLMStatus.READY && rag.status === RAGStatus.READY);
const promptSendable = computed(() => promptEnabled.value && promptValue.value.trim().length > 0);
const promptPlaceholder = computed(
    () =>
        ({
            [LLMStatus.LOADING]: t('assistant.input.loading'),
            [LLMStatus.GENERATING]: t('assistant.input.generating'),
            [LLMStatus.ERROR]: t('assistant.input.error'),
        })[llm.status] ?? (rag.status === RAGStatus.LOADING ? t('assistant.input.loading') : t('assistant.input')),
);

const mounted = ref(false);
const opened = ref(false);

const position = ref({ x: 0, y: 0 });
const viewportSize = ref({ w: 0, h: 0 });
const containerSize = computed(() => (opened.value ? props.dialogSize : props.triggerSize));

let resizeRaf = null;

const clampPosition = (x, y, targetOpened) => {
    const size = targetOpened ? props.dialogSize : props.triggerSize;

    return {
        x: Math.max(props.safePadding, Math.min(x, viewportSize.value.w - size.w - props.safePadding)),
        y: Math.max(props.safePadding, Math.min(y, viewportSize.value.h - size.h - props.safePadding)),
    };
};

const toggleOpen = () => {
    const nextOpened = !opened.value;
    let originX, originY, targetX, targetY;

    if (opened.value) {
        originX = position.value.x + props.dialogSize.w / 2;
        originY = position.value.y + props.dialogSize.h - props.triggerSize.h / 2;
    } else {
        originX = position.value.x + props.triggerSize.w / 2;
        originY = position.value.y + props.triggerSize.h / 2;
    }
    if (nextOpened) {
        targetX = originX - props.dialogSize.w / 2;
        targetY = originY - props.dialogSize.h + props.triggerSize.h / 2;
    } else {
        targetX = originX - props.triggerSize.w / 2;
        targetY = originY - props.triggerSize.h / 2;
    }

    position.value = clampPosition(targetX, targetY, nextOpened);
    opened.value = nextOpened;
};

const { dragging, onDragStart } = useDraggable({
    position,
    clamp: (x, y) => clampPosition(x, y, opened.value),
    onClick: toggleOpen,
});

const initRagIfNeeded = () => {
    if (!(opened.value && llm.status === LLMStatus.READY && [RAGStatus.IDLE, RAGStatus.ERROR].includes(rag.status))) {
        return;
    }

    rag.init().catch(() => {
        // RAG silently degrades to the base LLM flow.
    });
};

const handleRetry = () => {
    if (llm.status === LLMStatus.ERROR) {
        llm.retry();

        return;
    }
    if (rag.status === RAGStatus.ERROR) {
        initRagIfNeeded();
    }
};

const sendMessage = async () => {
    const content = promptValue.value.trim();

    if (!content || !promptSendable.value) {
        return;
    }

    promptValue.value = '';

    const ragResult = rag.status === RAGStatus.READY ? await rag.retrieve(content) : null;
    const systemPromptOverride = ragResult?.hit
        ? createRAGPrompt({
              basePrompt: DEFAULT_SYSTEM_PROMPT,
              topChunk: ragResult.topChunk,
          })
        : null;
    const { assistantMessageId, completed } = await llm.generate(
        content,
        systemPromptOverride
            ? {
                  systemPromptOverride,
              }
            : {},
    );

    if (completed && assistantMessageId && ragResult?.hit && ragResult.sources.length > 0) {
        llm.addSources(assistantMessageId, ragResult.sources);
    }
};

const handleWindowResize = () => {
    if (resizeRaf) return;
    resizeRaf = requestAnimationFrame(() => {
        viewportSize.value = { w: window.innerWidth, h: window.innerHeight };
        position.value = clampPosition(position.value.x, position.value.y, opened.value);
        resizeRaf = null;
    });
};

watch(opened, open => {
    if (open) {
        if (llm.status === LLMStatus.IDLE) {
            llm.init({ delay: 350 });
        } else {
            initRagIfNeeded();
        }
    } else {
        /**
         * 1. interrupt the generation
         * 2. cancel the initialization in 350ms
         */
        llm.interrupt();
    }
});

watch(
    () => llm.status,
    nextStatus => {
        if (nextStatus === LLMStatus.READY) {
            initRagIfNeeded();
        }
    },
);

watch(
    () => lang.value,
    async () => {
        await rag.dispose();
        initRagIfNeeded();
    },
);

onMounted(() => {
    mounted.value = true;
    viewportSize.value = { w: window.innerWidth, h: window.innerHeight };
    position.value = clampPosition(
        viewportSize.value.w - props.triggerSize.w - props.safePadding * 2,
        viewportSize.value.h - props.triggerSize.h - props.safePadding * 2,
        false,
    );
    window.addEventListener('resize', handleWindowResize);
});

onUnmounted(() => {
    window.removeEventListener('resize', handleWindowResize);

    if (resizeRaf) {
        cancelAnimationFrame(resizeRaf);
    }
    if (llm.status === LLMStatus.GENERATING) {
        llm.interrupt();
    }

    rag.dispose();
});
</script>
