// docs/.vitepress/theme/components/assistant/components/PromptBox.jsx
import { Button } from '@nild/components';
import { DynamicIcon } from '@nild/icons';
import { cnJoin } from '@nild/shared';
import React, { useEffect, useRef } from 'react';
import { useAssistantContext } from '../contexts/AssistantContext';
import ModelSelect from './ModelSelect';

const TEXTAREA_MIN_HEIGHT = 44;
const TEXTAREA_MAX_HEIGHT = 136;

const PromptBox = ({ value, disabled, generating, onChange, onSend }) => {
    const { i18n, locale } = useAssistantContext();
    const textareaRef = useRef(null);
    const sendable = !disabled && !generating && value.trim().length > 0;

    useEffect(() => {
        const textarea = textareaRef.current;

        if (!textarea) {
            return;
        }

        if (!value) {
            textarea.style.height = `${TEXTAREA_MIN_HEIGHT}px`;

            return;
        }

        textarea.style.height = `${TEXTAREA_MIN_HEIGHT}px`;
        textarea.style.height = `${Math.min(Math.max(textarea.scrollHeight, TEXTAREA_MIN_HEIGHT), TEXTAREA_MAX_HEIGHT)}px`;
    }, [value]);

    return (
        <div className="mx-4 mb-4 shrink-0 rounded-xl bg-subtle p-3 shadow-sm">
            <textarea
                ref={textareaRef}
                className={cnJoin(
                    'vp-custom-scrollbar block w-full resize-none border-0 p-0 outline-none leading-5.5',
                    'placeholder:text-subtle text-main text-md',
                    'max-h-34 min-h-11 overflow-y-auto',
                    disabled && 'cursor-not-allowed opacity-60',
                )}
                disabled={disabled}
                rows={2}
                value={value}
                placeholder={i18n.t(
                    generating
                        ? 'assistant.input.generating'
                        : disabled
                          ? 'assistant.input.disconnected'
                          : 'assistant.input',
                    { language: locale },
                )}
                onChange={event => onChange(event.target.value)}
                onKeyDown={event => {
                    if (event.key === 'Enter' && !event.shiftKey) {
                        event.preventDefault();
                        if (sendable) {
                            onSend();
                        }
                    }
                }}
            />
            <div className="mt-3 flex h-8 items-end justify-between gap-3">
                <ModelSelect disabled={disabled || generating} />
                <Button
                    equal
                    size="medium"
                    className="rounded-lg"
                    disabled={!sendable}
                    aria-label={i18n.t('assistant.send', { language: locale })}
                    onClick={onSend}
                >
                    <DynamicIcon name="send" variant="filled" />
                </Button>
            </div>
        </div>
    );
};

export default PromptBox;

// docs/.vitepress/theme/components/assistant/PromptBox.vue
<template>
    <div class="shrink-0 bg-page border-t border-muted flex gap-2 px-3 py-2.5">
        <textarea
            ref="textareaRef"
            :value="modelValue"
            rows="1"
            :class="[
                'flex-1 resize-none bg-transparent outline-none border-0 leading-5.5',
                'placeholder:text-subtle text-main text-md',
                'vp-custom-scrollbar max-h-28 overflow-y-auto',
                disabled ? 'cursor-not-allowed opacity-60' : '',
            ]"
            :placeholder="placeholder"
            :disabled="disabled"
            @input="handleInput"
            @keydown.enter.exact.prevent="handleSend"
        />
        <button
            :class="[
                'self-end shrink-0 w-8 h-8 rounded-lg flex items-center justify-center',
                'bg-brand text-brand-contrast transition-[opacity,background-color]',
                'enabled:hover:bg-brand-hover',
                'enabled:active:bg-brand-active',
                sendable ? 'cursor-pointer' : 'opacity-50 cursor-not-allowed',
            ]"
            :disabled="!sendable"
            @click="handleSend"
        >
            <SendIcon class="size-[15px]" />
        </button>
    </div>
</template>

<script setup>
import { ref, watch } from 'vue';
import SendIcon from '../../icons/send.svg';

const props = defineProps({
    modelValue: { type: String, default: '' },
    placeholder: { type: String, default: 'Message…' },
    disabled: { type: Boolean, default: false },
    sendable: { type: Boolean, default: false },
});

const emit = defineEmits(['update:modelValue', 'send']);

const textareaRef = ref(null);

const autoResize = () => {
    const el = textareaRef.value;

    if (!el) return;
    el.style.height = 'auto';
    el.style.height = `${el.scrollHeight}px`;
};

const handleInput = e => {
    emit('update:modelValue', e.target.value);
    autoResize();
};

const handleSend = () => emit('send');

/**
 * when value is cleared, reset the textarea height
 */
watch(
    () => props.modelValue,
    val => {
        if (!val && textareaRef.value) textareaRef.value.style.height = 'auto';
    },
);
</script>
